# Launch the OpenAI Codex DESKTOP app with a separate CODEX_HOME
# (~/.codex-tinyllm by default) so it talks through codex-router-proxy,
# while the main app (~/.codex) stays untouched.
#
# Why this dance: the desktop app is an MSIX package. Launching Codex.exe
# directly is blocked by package ACLs, and Invoke-CommandInDesktopPackage
# (which grants package identity) does NOT propagate the caller's
# environment. So we generate a small inner .cmd that sets CODEX_HOME
# itself and starts Codex.exe as its child (the child inherits it).
# Note: the app enforces a single-instance mutex, so this instance and
# the main one are sequential - quit one (tray included) to use the other.
#
# Usage: .\start-codex-tinyllm.ps1 [-CodexHome <path>] [-PackageName OpenAI.Codex] [-DryRun]
param(
    [string]$CodexHome = (Join-Path $HOME ".codex-tinyllm"),
    [string]$PackageName = "OpenAI.Codex",
    [string]$AppId = "App",
    [switch]$DryRun
)
$ErrorActionPreference = "Stop"

# 1. The alternate Codex home must already be wired: config.toml with the
#    codex-router-proxy provider table (see the capability snippet).
$config = Join-Path $CodexHome "config.toml"
if (-not (Test-Path -LiteralPath $config)) {
    Write-Host "config.toml not found at:" -ForegroundColor Red
    Write-Host "  $config"
    Write-Host ""
    Write-Host "Create the home first: copy the capability snippet"
    Write-Host "(~/.codex/codex-router/codex-config-snippet.toml) there as"
    Write-Host "config.toml, then set at the top:"
    Write-Host ""
    Write-Host '  model_provider = "codex-router-proxy"'
    Write-Host '  model = "your-model"'
    exit 1
}

# 2. The desktop package must be installed for the current user.
$pkg = Get-AppxPackage -Name $PackageName
if (-not $pkg) {
    Write-Host "Appx package '$PackageName' not found (is the Codex desktop app installed?)" -ForegroundColor Red
    exit 1
}
$exe = Join-Path $pkg.InstallLocation "app\Codex.exe"
if (-not (Test-Path -LiteralPath $exe)) {
    Write-Host "Codex.exe not found at:" -ForegroundColor Red
    Write-Host "  $exe"
    exit 1
}

# 3. Generate the inner launcher. It runs INSIDE package identity, where
#    the broker has dropped our environment, so CODEX_HOME is set here.
#    The temp file is intentionally left behind (unique per run) to avoid
#    a race with the freshly spawned cmd.exe reading it.
$inner = Join-Path $env:TEMP ("codex-tinyllm-inner-{0}.cmd" -f $PID)
@"
@echo off
rem Generated by start-codex-tinyllm.ps1 - do not edit.
set "CODEX_HOME=$CodexHome"
start "" "$exe"
"@ | Set-Content -LiteralPath $inner -Encoding Ascii

if ($DryRun) {
    Write-Host "[dry-run] inner launcher: $inner"
    Get-Content -LiteralPath $inner
    Write-Host "[dry-run] broker args: /c call `"$inner`""
    exit 0
}

# 4. Launch with package identity. -Args takes a single string only.
Invoke-CommandInDesktopPackage -PackageFamilyName $pkg.PackageFamilyName -AppId $AppId -Command "$env:SystemRoot\System32\cmd.exe" -Args "/c call `"$inner`""
